# Generated by Django 3.2.6 on 2021-08-20 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('My_todo_app', '0003_auto_20210820_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
