# Generated by Django 3.2.6 on 2021-08-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_todo_app', '0009_todocategoerymapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoery',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='TodoCategoeryMapping',
            new_name='TodoCategoryMapping',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoery_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='todocategorymapping',
            old_name='categoery',
            new_name='category',
        ),
    ]
