# Generated by Django 3.2.6 on 2021-08-23 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_todo_app', '0010_auto_20210823_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMassages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_title', models.CharField(max_length=200)),
                ('massage_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_send', models.IntegerField()),
                ('sand_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_todo_app.notificationmassages')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_todo_app.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
