# Generated by Django 3.2.6 on 2021-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_todo_app', '0011_auto_20210823_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
