# Generated by Django 3.2.6 on 2021-08-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_todo_app', '0012_auto_20210823_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmassages',
            name='massage_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
