# Generated by Django 3.2.6 on 2021-08-26 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('My_todo_app', '0014_auto_20210825_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
